ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"

platform :ios do
  def loadiOSConfigs()
    @package_name = ENV["PACKAGE_NAME"]
    @workspace_name = ENV["PRODUCT_NAME"]
    @project_name = "App"
    @keychain_name = ENV["IOS_KEYCHAIN"]
    @keychain_password = ENV["IOS_KEYCHAIN_PWD"]
    @certificate_path = ENV["IOS_CERT_PATH"]
    @certificate_password = ENV["IOS_CERT_PWD"]
    @provisioning_profile_path = ENV["IOS_PROFILE_PATH"]
    @team_id = ENV["APPLE_TEAM_ID"]
    @api_key_path = ENV["IOS_KEY_PATH"]
    @xcodeproj = "./Projects/#{@project_name}/#{@project_name}.xcodeproj"
    @profile_name = ENV["PROFILE_NAME"]
    @ipa_path = ENV["IOS_IPA_PATH"]

    puts "프로젝트: #{@project_name}"
    puts "API 키 경로: #{@api_key_path}"
  end

  def installCert
    create_keychain(
      name: @keychain_name,
      password: @keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true,
    )

    import_certificate(
      certificate_path: @certificate_path,
      certificate_password: @certificate_password,
      keychain_name: @keychain_name,
      keychain_password: @keychain_password,
    )

    puts "인증서 설치 완료"
  end

  def readySigning
    installCert()

    install_provisioning_profile(
      path: @provisioning_profile_path
    )
    puts "Provisioning Profile 설치 완료"

    update_code_signing_settings(
      use_automatic_signing: false,
      path: @xcodeproj,
      team_id: @team_id,
      code_sign_identity: "Apple Distribution",
      profile_name: @profile_name
    )
    puts "Code Signing 수동 전환 완료"
  end

  def setiOSVersions
    @app_version = get_version_number(
      xcodeproj: @xcodeproj,
      target: @project_name
    )
    puts "앱 버전: #{@app_version}"

    @build_version = latest_testflight_build_number(
      version: @app_version,
      api_key_path: @api_key_path,
      app_identifier: @package_name,
      initial_build_number: 0
    )

    @new_build_version = @build_version + 1
    increment_build_number(
      xcodeproj: @xcodeproj,
      build_number: @new_build_version
    )
    puts "빌드번호 상향: #{@build_version} => #{@new_build_version}"
  end

  lane :setup do
    loadiOSConfigs()
    readySigning()
    setiOSVersions()

    puts "인증서 설치 및 버전 설정 완료"
  end

  lane :upload do |options|
    loadiOSConfigs()

    isReleasing = options[:isReleasing] || false
    changelog = options[:description] || 'build from fastlane'

    if isReleasing
      puts "App Store 심사 업로드 시작"
      upload_to_app_store(
        ipa: @ipa_path,
        api_key_path: @api_key_path,
        app_identifier: @package_name,
        submit_for_review: true,
      )
      puts "심사 제출 완료"
    else
      puts "TestFlight 업로드 시작"
      upload_to_testflight(
        ipa: @ipa_path,
        api_key_path: @api_key_path,
        changelog: changelog,
        app_identifier: @package_name,
        skip_waiting_for_build_processing: true
      )
      puts "TestFlight 배포 완료"
    end
  end
end
